### ISSUE TITLE
stopping monitor causes penn_daq to crash

### ISSUE THREAD

**Issue by knapik** [pennsnoplus/snotstreamtest#9]
When running snot_mon with porca running Penn_daq will crash when a <stop xl3 localhost 44598> command is given.

You can start and stop the monitor connection just fine, when PORCA is not running, but when it is Penn_daq will crash when you try and stop the monitor.

**Comment by peterldowns** [comment]
This is an error with penn_daq, not snot_mon - all monitoring connections are closed appropriately before exit.
